### ISSUE TITLE
Is it possible to select the output device ?

### ISSUE THREAD

**Issue by arthurmchr** [YellowInnovation/node-rodio#1]
Hi,

Sorry for posting this here but I would like to know if it's possible to select the output device on which the player will play. Is there any parameter to select the device ?

Thanks !

**Comment by OtaK** [comment]
Hey!

Not possible at the moment no, as https://github.com/YellowInnovation/node-rodio/blob/master/native/src/lib.rs#L23 shows, we pick the device's default output for now.

Of course this can be changed.

Thanks!

**Comment by arthurmchr** [comment]
Thanks for your answer and your work :)
